### ISSUE TITLE
Ti unisci a Open Data Sicilia?

### ISSUE THREAD

**Issue by dennisangemi** [Gangelo99/Sismicita-Sicilia#1]
Ciao @Gangelo99,
questa non è una vera issue, ti scrivo solo per segnalarti che qui in Sicilia esiste una bellissima comunità Ope Data che (guarda caso) si chiama Open Data Sicilia ;)

Magari, se sei interessato al tema, potrati unirti a noi.

Ti lascio qui il link del gruppo telegram https://t.me/opendatasicilia ma ci trovi anche su https://opendatasicilia.it e altrove (@opendatasicilia)

Grazie @Helias per la segnalazione <3

**Comment by angelof-exe** [comment]
Ciao grazie per l'invito, entrerò con piacere 😊
